### PR TITLE
Browser extension and views fixes

### PR DESCRIPTION
**Pull request by Dinoosauro**

### CODE REVIEW

**Comment by jeffscottward** [comment]
tested and works great but even at 2500/4000 i think im being rate limited.

also this but didnt affect anythig.
Screenshot 2024-06-26 at 10 55 06 AM

**Comment by jeffscottward** [comment]
Also, I just remembered that I will need formats to save other than .txt.

**Comment by Dinoosauro** [comment]
I don't know if the throttling is due to a rate limit or not. TikTok doesn't clean up the HTML nodes of the previous videos, so the webpage in general might become really laggy on videos. There's not much we can do in that situation – the website seems to be based in React, and messing with the DOM by deleting previous nodes might break the re-render code

By the way, I've added in this new release support for JSON outputs. The downloaded file is a JSON array that contains the URL, the description and the views of the video. In case you only need one of these properties (I think especially video URLs), currently you can map the JSON after parsing it. Maybe tomorrow I could add another tab where the user can customize the output of the JSON format

**Comment by Dinoosauro** [comment]
I forgot to write in the message above that the error given by Chrome it's normal. That's a property of the manifest that is required for Firefox, and Chromium-based browsers will just ignore it

**Comment by jeffscottward** [comment]
Well upping the times on both seemed to solve it haha

Yes please for the JSON output. I just need an array but would be nice to
not have to do transforms for anyone else who needs labeling.

And yup figured as much with the Gecko reference.

*Thanks,*
*Jeff Ward*
*Front-end Developer*
*Tel: 516-551-8624*
***@***.*** ***@***.***>*
***@***.**** <https://twitter.com/#!/jeffscottward>

**Pull request merged**
